version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/.github/actions'
    schedule:
      interval: daily
      time: '07:00'
      timezone: Pacific/Midway
  - package-ecosystem: 'github-actions'
    directory: '/.github/workflows'
    schedule:
      interval: daily
      time: '07:00'
      timezone: Pacific/Midway
