version: 2

schedule:
  interval: daily
  time: '07:00'
  timezone: Pacific/Midway

updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: daily
      time: '07:00'
      timezone: Pacific/Midway
  - package-ecosystem: 'github-actions'
    directory: '/nested'
    schedule:
      interval: daily
      time: '07:00'
      timezone: Pacific/Midway
